package apperror

const (
  UsecaseNameMustNotEmpty ErrorType = "ER1000 usecase name must not empty" // UsecaseNameMustNotEmpty ...
  EntityNameMustNotEmpty  ErrorType = "ER1000 entity name must not empty"  // EntityNameMustNotEmpty ...
  ErrorNameMustNotEmpty   ErrorType = "ER1000 error name must not empty"   // ErrorNameMustNotEmpty ...
)
